### PR TITLE
Make sure directory exists before deploy vmlinux

### PR DESCRIPTION
**Pull request by iartemenko**
Signed-off-by: Iurii Artemenko <iurii_artemenko@epam.com>

### CODE REVIEW

**Comment by andr2000** [comment]
I would love to see the explanation for this fix in the commit message at least
That way it will be easier to understand this change

**Comment by iartemenko** [comment]
Done

**Review by andr2000 — APPROVED** [review]
Approved as yet another workaround
I think we have to figure out how to do this the right way

**Comment by aanisov** [comment]
wouldn't `find ${STAGING_KERNEL_BUILDDIR} -iname "vmlinux*" -exec mv {} ${DEPLOY_DIR_IMAGE} \; || true` work here?

**Pull request merged**
